# Generated by Django 4.2.30 on 2026-07-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_attachment_message_attachment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='category',
            field=models.CharField(default='Personal', max_length=50),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='persona',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, default='New Chat', max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='is_liked',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
